config/routes.rb
Rails.application.routes.draw do
  resources :news, except: [:index]
  get "home/index"
  get '/news', to: 'news#index', as: 'user_root'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "news#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :news
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        new_news_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)
    @news.user = current_user #o @news.user_id = current_user.id

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news), notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    def set_users
      @users = User.all.pluck :email
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:detail, :author, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Therialnews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :detail, style: "display: block" %>
    <%= form.text_area :detail %>
  </div>
  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author, value: current_user.email, readonly: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div id="<%= dom_id news %>">
  <p>
    <strong>Noticia:</strong>
    <%= news.detail %>
  </p>
  <p>
    <strong>Autor:</strong>
    <%= news.author %>
  </p>

</div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Show this news", @news %> |
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Noticias</h1>
<%= link_to "Crear Nueva Noticia", new_news_path %>

<table class="table" id="news">
  <thead>
    <tr>
      <th scope="col">N°</th>
      <th scope="col">Noticia</th>
      <th scope="col">Autor</th>
      <th scope="col">ver</th>
    </tr>
  </thead>
  <tbody>
    <% @news.each do |news| %>
    <tr>
      <th scope="row">1</th>
      <td><%=news.detail.byteslice(0, 60)%>...</td>
      <td><%=news.author%></td>
      <td><%= link_to "Mostrar toda la Noticia", news %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/news/new.html.erb
<h1>Nueva Noticia</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @news %>

<div>
  <%= link_to "Back to news", news_index_path %>
  <% if user_signed_in? %>
    <% if current_user.id == @news.user_id %>
      <%= link_to "Edit this news", edit_news_path(@news) %> |
      <%= button_to "Destroy this news", @news, method: :delete %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <%= link_to 'TheRialNews', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Noticias', new_news_path, class: 'nav-link' %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <% if user_signed_in? %>
                            Hola <%= current_user.email %>
                        <% else %>
                            Dale registrate o conectate
                        <% end %>
                    </a>
                    <ul class="dropdown-menu">
                    <% if user_signed_in? %>
                        <li><%= link_to 'Ver Notocias', new_news_path, class: 'dropdown-item'%></li>
                        <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                    <% else %>
                        <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
                    <% end %>
                    </ul>
                </li>
        </div>
    </div>
</nav>